void models_details_c_(){
strcpy(models[0].model_path,"GMI_ONNX_Models/dense_autoencoder_land.onnx");
printf("model[0] =%s \n",models[0].model_path);
strcpy(models[0].inputs[0].name,"input");
models[0].inputs[0].shape_len=2;
models[0].inputs[0].n_elem=11;
models[0].inputs[0].shape[0]=1;
models[0].inputs[0].shape[1]=11;
models[0].inputs[0].dtype=1;
models[0].input_data[0]=(float *) malloc(sizeof(float)*11);
models[0].num_inputs=1;
models[0].num_outputs=1;
strcpy(models[0].outputs[0].name,"output");
models[0].outputs[0].shape_len=2;
models[0].outputs[0].n_elem=11;
models[0].outputs[0].shape[0]=1;
models[0].outputs[0].shape[1]=11;
models[0].outputs[0].dtype=1;
models[0].output_data[0]=(float *) malloc(sizeof(float)*11);
strcpy(models[1].model_path,"GMI_ONNX_Models/dense_autoencoder_ocean.onnx");
printf("model[1] =%s \n",models[1].model_path);
strcpy(models[1].inputs[0].name,"input");
models[1].inputs[0].shape_len=2;
models[1].inputs[0].n_elem=11;
models[1].inputs[0].shape[0]=1;
models[1].inputs[0].shape[1]=11;
models[1].inputs[0].dtype=1;
models[1].input_data[0]=(float *) malloc(sizeof(float)*11);
models[1].num_inputs=1;
models[1].num_outputs=1;
strcpy(models[1].outputs[0].name,"output");
models[1].outputs[0].shape_len=2;
models[1].outputs[0].n_elem=11;
models[1].outputs[0].shape[0]=1;
models[1].outputs[0].shape[1]=11;
models[1].outputs[0].dtype=1;
models[1].output_data[0]=(float *) malloc(sizeof(float)*11);
strcpy(models[2].model_path,"GMI_ONNX_Models/dense_decoder_land.onnx");
printf("model[2] =%s \n",models[2].model_path);
strcpy(models[2].inputs[0].name,"enc_output");
models[2].inputs[0].shape_len=2;
models[2].inputs[0].n_elem=4;
models[2].inputs[0].shape[0]=1;
models[2].inputs[0].shape[1]=4;
models[2].inputs[0].dtype=1;
models[2].input_data[0]=(float *) malloc(sizeof(float)*4);
models[2].num_inputs=1;
models[2].num_outputs=1;
strcpy(models[2].outputs[0].name,"dec_output");
models[2].outputs[0].shape_len=2;
models[2].outputs[0].n_elem=11;
models[2].outputs[0].shape[0]=1;
models[2].outputs[0].shape[1]=11;
models[2].outputs[0].dtype=1;
models[2].output_data[0]=(float *) malloc(sizeof(float)*11);
strcpy(models[3].model_path,"GMI_ONNX_Models/dense_decoder_ocean.onnx");
printf("model[3] =%s \n",models[3].model_path);
strcpy(models[3].inputs[0].name,"enc_output");
models[3].inputs[0].shape_len=2;
models[3].inputs[0].n_elem=4;
models[3].inputs[0].shape[0]=1;
models[3].inputs[0].shape[1]=4;
models[3].inputs[0].dtype=1;
models[3].input_data[0]=(float *) malloc(sizeof(float)*4);
models[3].num_inputs=1;
models[3].num_outputs=1;
strcpy(models[3].outputs[0].name,"dec_output");
models[3].outputs[0].shape_len=2;
models[3].outputs[0].n_elem=11;
models[3].outputs[0].shape[0]=1;
models[3].outputs[0].shape[1]=11;
models[3].outputs[0].dtype=1;
models[3].output_data[0]=(float *) malloc(sizeof(float)*11);
strcpy(models[4].model_path,"GMI_ONNX_Models/dense_encoder_land.onnx");
printf("model[4] =%s \n",models[4].model_path);
strcpy(models[4].inputs[0].name,"input");
models[4].inputs[0].shape_len=2;
models[4].inputs[0].n_elem=11;
models[4].inputs[0].shape[0]=1;
models[4].inputs[0].shape[1]=11;
models[4].inputs[0].dtype=1;
models[4].input_data[0]=(float *) malloc(sizeof(float)*11);
models[4].num_inputs=1;
models[4].num_outputs=1;
strcpy(models[4].outputs[0].name,"enc_output");
models[4].outputs[0].shape_len=2;
models[4].outputs[0].n_elem=4;
models[4].outputs[0].shape[0]=1;
models[4].outputs[0].shape[1]=4;
models[4].outputs[0].dtype=1;
models[4].output_data[0]=(float *) malloc(sizeof(float)*4);
strcpy(models[5].model_path,"GMI_ONNX_Models/dense_encoder_ocean.onnx");
printf("model[5] =%s \n",models[5].model_path);
strcpy(models[5].inputs[0].name,"input");
models[5].inputs[0].shape_len=2;
models[5].inputs[0].n_elem=11;
models[5].inputs[0].shape[0]=1;
models[5].inputs[0].shape[1]=11;
models[5].inputs[0].dtype=1;
models[5].input_data[0]=(float *) malloc(sizeof(float)*11);
models[5].num_inputs=1;
models[5].num_outputs=1;
strcpy(models[5].outputs[0].name,"enc_output");
models[5].outputs[0].shape_len=2;
models[5].outputs[0].n_elem=4;
models[5].outputs[0].shape[0]=1;
models[5].outputs[0].shape[1]=4;
models[5].outputs[0].dtype=1;
models[5].output_data[0]=(float *) malloc(sizeof(float)*4);
strcpy(models[6].model_path,"GMI_ONNX_Models/land_model.onnx");
printf("model[6] =%s \n",models[6].model_path);
strcpy(models[6].inputs[0].name,"input");
models[6].inputs[0].shape_len=4;
models[6].inputs[0].n_elem=139650;
models[6].inputs[0].shape[0]=1;
models[6].inputs[0].shape[1]=19;
models[6].inputs[0].shape[2]=150;
models[6].inputs[0].shape[3]=49;
models[6].inputs[0].dtype=1;
models[6].input_data[0]=(float *) malloc(sizeof(float)*139650);
models[6].num_inputs=1;
models[6].num_outputs=2;
strcpy(models[6].outputs[0].name,"output_rec");
models[6].outputs[0].shape_len=4;
models[6].outputs[0].n_elem=95550;
models[6].outputs[0].shape[0]=1;
models[6].outputs[0].shape[1]=13;
models[6].outputs[0].shape[2]=150;
models[6].outputs[0].shape[3]=49;
models[6].outputs[0].dtype=1;
models[6].output_data[0]=(float *) malloc(sizeof(float)*95550);
strcpy(models[6].outputs[1].name,"output_pred");
models[6].outputs[1].shape_len=4;
models[6].outputs[1].n_elem=88200;
models[6].outputs[1].shape[0]=1;
models[6].outputs[1].shape[1]=12;
models[6].outputs[1].shape[2]=150;
models[6].outputs[1].shape[3]=49;
models[6].outputs[1].dtype=1;
models[6].output_data[1]=(float *) malloc(sizeof(float)*88200);
strcpy(models[7].model_path,"GMI_ONNX_Models/ocean_model.onnx");
printf("model[7] =%s \n",models[7].model_path);
strcpy(models[7].inputs[0].name,"input");
models[7].inputs[0].shape_len=4;
models[7].inputs[0].n_elem=139650;
models[7].inputs[0].shape[0]=1;
models[7].inputs[0].shape[1]=19;
models[7].inputs[0].shape[2]=150;
models[7].inputs[0].shape[3]=49;
models[7].inputs[0].dtype=1;
models[7].input_data[0]=(float *) malloc(sizeof(float)*139650);
models[7].num_inputs=1;
models[7].num_outputs=2;
strcpy(models[7].outputs[0].name,"output_rec");
models[7].outputs[0].shape_len=4;
models[7].outputs[0].n_elem=95550;
models[7].outputs[0].shape[0]=1;
models[7].outputs[0].shape[1]=13;
models[7].outputs[0].shape[2]=150;
models[7].outputs[0].shape[3]=49;
models[7].outputs[0].dtype=1;
models[7].output_data[0]=(float *) malloc(sizeof(float)*95550);
strcpy(models[7].outputs[1].name,"output_pred");
models[7].outputs[1].shape_len=4;
models[7].outputs[1].n_elem=88200;
models[7].outputs[1].shape[0]=1;
models[7].outputs[1].shape[1]=12;
models[7].outputs[1].shape[2]=150;
models[7].outputs[1].shape[3]=49;
models[7].outputs[1].dtype=1;
models[7].output_data[1]=(float *) malloc(sizeof(float)*88200);
}
